import { customType, timestamp, uuid } from 'drizzle-orm/pg-core';
import { uuidv7 } from 'uuidv7';

/** Case-insensitive text (needs the citext extension; see the first migration). */
export const citext = customType<{ data: string }>({
  dataType: () => 'citext',
});

export const bytea = customType<{ data: Buffer }>({
  dataType: () => 'bytea',
});

/** UUIDv7 primary key, generated by the API so ids sort by creation time. */
export const id = () =>
  uuid('id')
    .primaryKey()
    .$defaultFn(() => uuidv7());

export const ts = (name: string) => timestamp(name, { withTimezone: true });

export const createdAt = () => ts('created_at').notNull().defaultNow();
