// Generated from apps/mobile/lib/data.dart (the app's catalog, ranks low → high).
// hasRanks false = the ladder is play-style levels, not competitive ranks.
// isLaunch is provisional until the validation test picks the launch games.
// maxParty: largest party a listing can ask for in that game.

export interface SeedGame {
  id: string;
  name: string;
  shortCode: string;
  platforms: ('pc' | 'playstation' | 'xbox' | 'mobile' | 'switch')[];
  hasRanks: boolean;
  ranks: string[];
  maxParty: number;
  isLaunch: boolean;
}

export const seedGames: SeedGame[] = [
  {
    id: 'val',
    name: 'Valorant',
    shortCode: 'VAL',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: [
      'Iron',
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Diamond',
      'Ascendant',
      'Immortal',
      'Radiant',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'lol',
    name: 'League of Legends',
    shortCode: 'LoL',
    platforms: ['pc'],
    hasRanks: true,
    ranks: [
      'Iron',
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Emerald',
      'Diamond',
      'Master',
      'Grandmaster',
      'Challenger',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'cs2',
    name: 'Counter-Strike 2',
    shortCode: 'CS2',
    platforms: ['pc'],
    hasRanks: true,
    ranks: [
      'Grey · 0–4,999',
      'Light Blue · 5,000+',
      'Blue · 10,000+',
      'Purple · 15,000+',
      'Pink · 20,000+',
      'Red · 25,000+',
      'Gold · 30,000+',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'dota',
    name: 'Dota 2',
    shortCode: 'DOTA',
    platforms: ['pc'],
    hasRanks: true,
    ranks: ['Herald', 'Guardian', 'Crusader', 'Archon', 'Legend', 'Ancient', 'Divine', 'Immortal'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'fn',
    name: 'Fortnite',
    shortCode: 'FN',
    platforms: ['pc', 'playstation', 'xbox', 'switch', 'mobile'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Elite', 'Champion', 'Unreal'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'apex',
    name: 'Apex Legends',
    shortCode: 'APEX',
    platforms: ['pc', 'playstation', 'xbox', 'switch'],
    hasRanks: true,
    ranks: ['Rookie', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Master', 'Apex Predator'],
    maxParty: 3,
    isLaunch: false,
  },
  {
    id: 'ow',
    name: 'Overwatch',
    shortCode: 'OW',
    platforms: ['pc', 'playstation', 'xbox', 'switch'],
    hasRanks: true,
    ranks: [
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Diamond',
      'Master',
      'Grandmaster',
      'Champion',
      'Top 500',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'rivals',
    name: 'Marvel Rivals',
    shortCode: 'MR',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: [
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Diamond',
      'Grandmaster',
      'Celestial',
      'Eternity',
      'One Above All',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'r6',
    name: 'Rainbow Six Siege X',
    shortCode: 'R6',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: ['Copper', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Emerald', 'Diamond', 'Champion'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'bo7',
    name: 'Call of Duty: Black Ops 7',
    shortCode: 'BO7',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Crimson', 'Iridescent', 'Top 250'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'wz',
    name: 'Call of Duty: Warzone',
    shortCode: 'WZ',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Crimson', 'Iridescent', 'Top 250'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'pubgpc',
    name: 'PUBG: Battlegrounds',
    shortCode: 'PUBG',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Master', 'Top 500'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'rl',
    name: 'Rocket League',
    shortCode: 'RL',
    platforms: ['pc', 'playstation', 'xbox', 'switch'],
    hasRanks: true,
    ranks: [
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Diamond',
      'Champion',
      'Grand Champion',
      'Supersonic Legend',
    ],
    maxParty: 3,
    isLaunch: false,
  },
  {
    id: 'deadlock',
    name: 'Deadlock',
    shortCode: 'DL',
    platforms: ['pc'],
    hasRanks: true,
    ranks: [
      'Initiate',
      'Seeker',
      'Alchemist',
      'Arcanist',
      'Ritualist',
      'Emissary',
      'Archon',
      'Oracle',
      'Phantom',
      'Ascendant',
      'Eternus',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'fc',
    name: 'EA SPORTS FC',
    shortCode: 'FC',
    platforms: ['pc', 'playstation', 'xbox', 'switch'],
    hasRanks: true,
    ranks: [
      'Div 10',
      'Div 9',
      'Div 8',
      'Div 7',
      'Div 6',
      'Div 5',
      'Div 4',
      'Div 3',
      'Div 2',
      'Div 1',
      'Elite',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'efootball',
    name: 'eFootball',
    shortCode: 'EFB',
    platforms: ['pc', 'playstation', 'xbox', 'switch', 'mobile'],
    hasRanks: true,
    ranks: [
      'Div 10',
      'Div 9',
      'Div 8',
      'Div 7',
      'Div 6',
      'Div 5',
      'Div 4',
      'Div 3',
      'Div 2',
      'Div 1',
    ],
    maxParty: 5,
    isLaunch: true,
  },
  {
    id: 'tft',
    name: 'Teamfight Tactics',
    shortCode: 'TFT',
    platforms: ['pc', 'mobile'],
    hasRanks: true,
    ranks: [
      'Iron',
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Emerald',
      'Diamond',
      'Master',
      'Grandmaster',
      'Challenger',
    ],
    maxParty: 2,
    isLaunch: false,
  },
  {
    id: 'hs',
    name: 'Hearthstone',
    shortCode: 'HS',
    platforms: ['pc', 'mobile'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Legend'],
    maxParty: 2,
    isLaunch: false,
  },
  {
    id: 'tekken',
    name: 'Tekken 8',
    shortCode: 'T8',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: [
      'Beginner',
      '1st Dan',
      '2nd Dan',
      'Fighter',
      'Strategist',
      'Combatant',
      'Brawler',
      'Ranger',
      'Cavalry',
      'Warrior',
      'Assailant',
      'Dominator',
      'Vanquisher',
      'Destroyer',
      'Eliminator',
      'Garyu',
      'Shinryu',
      'Tenryu',
      'Mighty Ruler',
      'Flame Ruler',
      'Battle Ruler',
      'Fujin',
      'Raijin',
      'Kishin',
      'Bushin',
      'Tekken King',
      'Tekken Emperor',
      'Tekken God',
      'Tekken God Supreme',
      'God of Destruction',
    ],
    maxParty: 2,
    isLaunch: false,
  },
  {
    id: 'sf6',
    name: 'Street Fighter 6',
    shortCode: 'SF6',
    platforms: ['pc', 'playstation', 'xbox', 'switch'],
    hasRanks: true,
    ranks: [
      'Rookie',
      'Iron',
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Diamond',
      'Master',
      'High Master',
      'Grand Master',
      'Ultimate Master',
      'Legend',
    ],
    maxParty: 2,
    isLaunch: false,
  },
  {
    id: 'halo',
    name: 'Halo Infinite',
    shortCode: 'HALO',
    platforms: ['pc', 'xbox'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Onyx'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'finals',
    name: 'The Finals',
    shortCode: 'TF',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Ruby'],
    maxParty: 3,
    isLaunch: false,
  },
  {
    id: 'splatoon',
    name: 'Splatoon 3',
    shortCode: 'SPL3',
    platforms: ['switch'],
    hasRanks: true,
    ranks: ['C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+', 'S', 'S+'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'dbd',
    name: 'Dead by Daylight',
    shortCode: 'DBD',
    platforms: ['pc', 'playstation', 'xbox', 'switch', 'mobile'],
    hasRanks: true,
    ranks: ['Ash', 'Bronze', 'Silver', 'Gold', 'Iridescent'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'codm',
    name: 'CoD Mobile',
    shortCode: 'CODM',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: ['Rookie', 'Veteran', 'Elite', 'Pro', 'Master', 'Grandmaster', 'Legendary'],
    maxParty: 5,
    isLaunch: true,
  },
  {
    id: 'pubg',
    name: 'PUBG Mobile',
    shortCode: 'PUBGM',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: [
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Diamond',
      'Crown',
      'Ace',
      'Ace Master',
      'Ace Dominator',
      'Conqueror',
    ],
    maxParty: 4,
    isLaunch: true,
  },
  {
    id: 'ff',
    name: 'Free Fire',
    shortCode: 'FF',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Heroic', 'Master', 'Grandmaster'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'mlbb',
    name: 'Mobile Legends: Bang Bang',
    shortCode: 'MLBB',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: [
      'Warrior',
      'Elite',
      'Master',
      'Grandmaster',
      'Epic',
      'Legend',
      'Mythic',
      'Mythical Honor',
      'Mythical Glory',
      'Mythical Immortal',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'hok',
    name: 'Honor of Kings',
    shortCode: 'HOK',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: [
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Diamond',
      'Master',
      'Grandmaster',
      'Mythic',
      'Epic',
      'Legend',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'wr',
    name: 'LoL: Wild Rift',
    shortCode: 'WR',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: [
      'Iron',
      'Bronze',
      'Silver',
      'Gold',
      'Platinum',
      'Emerald',
      'Diamond',
      'Master',
      'Grandmaster',
      'Challenger',
      'Sovereign',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'bs',
    name: 'Brawl Stars',
    shortCode: 'BS',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: ['Bronze', 'Silver', 'Gold', 'Diamond', 'Mythic', 'Legendary', 'Masters', 'Pro'],
    maxParty: 3,
    isLaunch: false,
  },
  {
    id: 'coc',
    name: 'Clash of Clans',
    shortCode: 'COC',
    platforms: ['mobile'],
    hasRanks: true,
    ranks: [
      'Skeleton',
      'Barbarian',
      'Archer',
      'Wizard',
      'Valkyrie',
      'Witch',
      'Golem',
      'P.E.K.K.A',
      'Titan',
      'Dragon',
      'Electro',
      'Legend III',
      'Legend II',
      'Legend I',
    ],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'cr',
    name: 'Clash Royale',
    shortCode: 'CR',
    platforms: ['mobile'],
    hasRanks: false,
    ranks: ['Trophy Road', 'Path of Legends', 'Ultimate Champion'],
    maxParty: 2,
    isLaunch: false,
  },
  {
    id: 'unite',
    name: 'Pokémon UNITE',
    shortCode: 'UNITE',
    platforms: ['mobile', 'switch'],
    hasRanks: true,
    ranks: ['Beginner', 'Great', 'Expert', 'Veteran', 'Ultra', 'Master'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'mc',
    name: 'Minecraft',
    shortCode: 'MC',
    platforms: ['pc', 'playstation', 'xbox', 'switch', 'mobile'],
    hasRanks: false,
    ranks: ['Survival', 'Creative', 'Hardcore', 'PvP'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'roblox',
    name: 'Roblox',
    shortCode: 'RBX',
    platforms: ['pc', 'playstation', 'xbox', 'mobile'],
    hasRanks: false,
    ranks: ['Casual', 'Regular', 'Competitive'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'gta',
    name: 'GTA Online',
    shortCode: 'GTA',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['Casual', 'Grinder', 'Roleplay', 'Racing'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'elden',
    name: 'Elden Ring',
    shortCode: 'ER',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['Casual', 'Co-op', 'Challenge runs'],
    maxParty: 3,
    isLaunch: false,
  },
  {
    id: 'helldivers',
    name: 'Helldivers 2',
    shortCode: 'HD2',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['Difficulty 1–3', 'Difficulty 4–6', 'Difficulty 7–9', 'Super Helldive'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'bf6',
    name: 'Battlefield 6',
    shortCode: 'BF6',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['Casual', 'Regular', 'Competitive'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'arc',
    name: 'ARC Raiders',
    shortCode: 'ARC',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['Casual', 'Regular', 'Hardcore'],
    maxParty: 3,
    isLaunch: false,
  },
  {
    id: 'mhw',
    name: 'Monster Hunter Wilds',
    shortCode: 'MHW',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['HR 1–49', 'HR 50–99', 'HR 100+'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'genshin',
    name: 'Genshin Impact',
    shortCode: 'GI',
    platforms: ['pc', 'playstation', 'mobile'],
    hasRanks: false,
    ranks: ['AR 1–35', 'AR 36–50', 'AR 51–57', 'AR 58–60'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'nba2k',
    name: 'NBA 2K',
    shortCode: '2K',
    platforms: ['pc', 'playstation', 'xbox', 'switch'],
    hasRanks: false,
    ranks: ['Rookie', 'Pro', 'All-Star', 'Superstar', 'Legend'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'mkw',
    name: 'Mario Kart World',
    shortCode: 'MKW',
    platforms: ['switch'],
    hasRanks: false,
    ranks: ['Casual', 'Online regular', 'Competitive'],
    maxParty: 4,
    isLaunch: false,
  },
  {
    id: 'rust',
    name: 'Rust',
    shortCode: 'RUST',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['Casual', 'Regular', 'Hardcore'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'sot',
    name: 'Sea of Thieves',
    shortCode: 'SOT',
    platforms: ['pc', 'playstation', 'xbox'],
    hasRanks: false,
    ranks: ['Casual', 'Regular', 'Hardcore'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'amongus',
    name: 'Among Us',
    shortCode: 'AU',
    platforms: ['pc', 'playstation', 'xbox', 'switch', 'mobile'],
    hasRanks: false,
    ranks: ['Casual', 'Regular', 'Competitive'],
    maxParty: 5,
    isLaunch: false,
  },
  {
    id: 'fallguys',
    name: 'Fall Guys',
    shortCode: 'FG',
    platforms: ['pc', 'playstation', 'xbox', 'switch'],
    hasRanks: false,
    ranks: ['Casual', 'Regular', 'Competitive'],
    maxParty: 5,
    isLaunch: false,
  },
];
